### ISSUE TITLE
How to determine the JRE or JAVA_HOME location

### ISSUE THREAD

**Issue by hoshposh** [caf-archive/opensuse-java8-images#17]
It would be very useful and convenient to have an environment variable or other base-image defined configurable setting that provided the location of the JRE or JDK folder.

For our derived image, we use that location to be able to run an existing _installer_ during the image creation, without having to change the installer to no longer need the folder location.

Within the `Dockerfile` for this `opensuse-java8-images` image, there is an assumption that the location is `/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre`, and while our derived image could make the same assumption, it would be more convenient to rely on an environment variable so that our derived image would survive a future location change.

**Comment by hoshposh** [comment]
**Correction**: I see that `$JAVA_HOME` is defined on the JDK image, so this issue would be focused on a way to determine the JRE location via an environment variable.

**Comment by dermot-hardy** [comment]
Setting `JRE_HOME` seems like the most sensible thing to do here.

`JAVA_HOME` is intended to refer to the JDK location:
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars001.html

**Comment by dermot-hardy** [comment]
https://portal.digitalsafe.net/browse/SCMOD-9787

**Comment by dermot-hardy** [comment]
PR #18 opened for this.

**Comment by michael-bryson** [comment]
@hoshposh The latest snapshot of this now has a JRE_HOME environment variable in both the jre and jdk base image.
