### ISSUE TITLE
Tomcat is running as root

### ISSUE THREAD

**Issue by steve-williams-mf** [caf-archive/opensuse-java8-images#24]
We are seeing that Tomcat is running as root as compared to a service account.  An Application Server should not be run a root.

**Comment by michael-bryson** [comment]
@steve-williams-mf Have you logged this issue in the wrong repository, did you mean to log this in https://github.com/CAFapi/opensuse-tomcat-image or https://github.com/CAFapi/opensuse-tomcat-jre11-image instead? This repository does not have tomcat in it.

**Comment by steve-williams-mf** [comment]
Thanks @michael-bryson I will create it as necessary in the right project.  Sorry about the mistake.
